name: Pack

on:
  push:
    branches:
      - main

jobs:
  zip-and-pack:
    name: Zip and Pack
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Version
        id: version
        run: |
          echo "::set-output name=version::$(cat version)"

      - name: Zip
        run: |
          mkdir -p dist/
          zip -r dist/pack.zip bin/ config/ mods/ mystcraft/ patchouli_books/ resources/ scripts/

      - name: Pack
        id: pack
        uses: actions/upload-artifact@v3
        with:
          name: pack.zip
          path: dist/pack.zip
          if-no-files-found: error

      - name: Release
        uses: actions/create-release@v1
        id: release
        with:
          draft: false
          prerelease: false
          release_name: 1.12.2 Synpack v${{ steps.version.outputs.version }}
          tag_name: v${{ steps.version.outputs.version }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Publish
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: dist/pack.zip
          asset_name: 1.12.2-synpack-v${{ steps.version.outputs.version }}.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ github.token }}